# Build Stage
FROM node:20-alpine AS build
WORKDIR /app

# Install dependencies
COPY src/frontend/package*.json ./
RUN npm install

# Build the app
COPY src/frontend/ ./
RUN npm run build

# Final Stage
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/out ./out

EXPOSE 3000
CMD ["serve", "-s", "out", "-l", "3000"]
