# Build Stage
FROM node:18-alpine AS build
WORKDIR /app

# Install dependencies
COPY src/frontend/package*.json ./
RUN npm install

# Build the app
COPY src/frontend/ ./
RUN npm run build

# Final Stage
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/next.config.js ./
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]
