// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RandevuTakip.Api.Data;

#nullable disable

namespace RandevuTakip.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227085916_AddStaffSystem")]
    partial class AddStaffSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RandevuTakip.Api.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@demo.com",
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgdtsh7UUCV5pUtZTC0Esh9C6Z.G",
                            Role = "Owner",
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İlk kontrol ve ağız sağlığı değerlendirmesi.",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Genel Muayene",
                            Price = 500m,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("b2e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a2"),
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estetik dolgu işlemi.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Kompozit Dolgu",
                            Price = 1200m,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("b3e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a3"),
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Derinlemesine diş taşı ve plak temizliği.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Diş Taşı Temizliği",
                            Price = 800m,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            Bio = "15 yıllık deneyimli ortodonti uzmanı.",
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayse@demo.com",
                            IsActive = true,
                            Name = "Dr. Ayşe Yılmaz",
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            Title = "Başhekim / Ortodontist"
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.StaffService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffServices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            ServiceId = new Guid("b1e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            StaffId = new Guid("c0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("e1e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a2"),
                            ServiceId = new Guid("b2e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a2"),
                            StaffId = new Guid("c0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("e1e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a3"),
                            ServiceId = new Guid("b3e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a3"),
                            StaffId = new Guid("c0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingFormSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThemeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1"),
                            BookingFormSchema = "[{\"id\": \"complaint\", \"type\": \"textarea\", \"label\": \"Şikayetiniz\", \"required\": true}]",
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Dentist",
                            IsActive = true,
                            Name = "Örnek Diş Kliniği",
                            Slug = "dentist",
                            ThemeJson = "{\"primaryColor\": \"#4f46e5\", \"logoUrl\": \"\"}"
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.WorkingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<int>("SlotStepMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkingHours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            DayOfWeek = 1,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotStepMinutes = 30,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            DayOfWeek = 2,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotStepMinutes = 30,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            DayOfWeek = 3,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotStepMinutes = 30,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            DayOfWeek = 4,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotStepMinutes = 30,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            DayOfWeek = 5,
                            IsClosed = false,
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotStepMinutes = 30,
                            TenantId = new Guid("d0e3a6a1-a6a1-4a6a-a6a1-a6a1a6a1a6a1")
                        });
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Admin", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Appointment", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandevuTakip.Api.Models.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId");

                    b.HasOne("RandevuTakip.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Service", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Tenant", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Staff", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.StaffService", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandevuTakip.Api.Models.Staff", "Staff")
                        .WithMany("StaffServices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.WorkingHours", b =>
                {
                    b.HasOne("RandevuTakip.Api.Models.Staff", "Staff")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StaffId");

                    b.HasOne("RandevuTakip.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("StaffServices");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("RandevuTakip.Api.Models.Tenant", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
